[providers]
  node = {}
  go = {}

[phases.setup]
  nixPkgs = ["nodejs", "go"]

[phases.install]
  cmds = ["cd ui && npm install"]

[phases.build]
  cmds = [
    "cd ui && npm run build",
    "cd .. && go build -ldflags=\"-w -s\" -o out"
  ]

[start]
  cmd = "./out"
