package export

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/onboard-cli/internal/store"
)

// MermaidExporter implements Exporter for Mermaid.js
type MermaidExporter struct{}

func (m *MermaidExporter) Export(nodes []store.DBNode, edges []store.DBEdge) (string, error) {
	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("%% Generated by onboard-cli v1.0.0 at %s\n", time.Now().Format(time.RFC3339)))
	builder.WriteString("graph TD\n\n")

	// Group nodes by FilePath
	groups := make(map[string][]store.DBNode)
	for _, n := range nodes {
		groups[n.FilePath] = append(groups[n.FilePath], n)
	}

	// Write subgraphs
	for path, groupNodes := range groups {
		safePath := strings.ReplaceAll(path, "/", "_")
		safePath = strings.ReplaceAll(safePath, ".", "_")
		builder.WriteString(fmt.Sprintf("  subgraph cluster_%s[\"%s\"]\n", safePath, path))
		for _, n := range groupNodes {
			builder.WriteString(fmt.Sprintf("    %s[\"%s\"]\n", n.ID, n.Name))
		}
		builder.WriteString("  end\n\n")
	}

	// Write edges
	builder.WriteString("  %% Edges\n")
	for _, e := range edges {
		builder.WriteString(fmt.Sprintf("  %s -->|%s| %s\n", e.SourceID, e.RelationshipType, e.TargetID))
	}

	// Write styles
	builder.WriteString("\n  %% Styles\n")
	for _, n := range nodes {
		color := "#333333"
		switch strings.ToLower(n.Type) {
		case "function", "method":
			color = "#4CAF50" // Green
		case "class", "type":
			color = "#2196F3" // Blue
		}
		builder.WriteString(fmt.Sprintf("  style %s fill:%s,color:#fff\n", n.ID, color))
	}

	return builder.String(), nil
}

// DOTExporter implements Exporter for Graphviz DOT
type DOTExporter struct{}

func (d *DOTExporter) Export(nodes []store.DBNode, edges []store.DBEdge) (string, error) {
	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("// Generated by onboard-cli v1.0.0 at %s\n", time.Now().Format(time.RFC3339)))
	builder.WriteString("digraph G {\n")
	builder.WriteString("  node [shape=box, style=filled, fontname=\"Helvetica\"];\n\n")

	// Group nodes by FilePath
	groups := make(map[string][]store.DBNode)
	for _, n := range nodes {
		groups[n.FilePath] = append(groups[n.FilePath], n)
	}

	// Write subgraphs
	clusterIdx := 0
	for path, groupNodes := range groups {
		builder.WriteString(fmt.Sprintf("  subgraph cluster_%d {\n", clusterIdx))
		builder.WriteString(fmt.Sprintf("    label=\"%s\";\n", path))
		builder.WriteString("    style=dashed;\n")
		for _, n := range groupNodes {
			color := "lightgrey"
			switch strings.ToLower(n.Type) {
			case "function", "method":
				color = "lightgreen"
			case "class", "type":
				color = "lightblue"
			}
			builder.WriteString(fmt.Sprintf("    \"%s\" [label=\"%s\", fillcolor=\"%s\"];\n", n.ID, n.Name, color))
		}
		builder.WriteString("  }\n\n")
		clusterIdx++
	}

	// Write edges
	builder.WriteString("  // Edges\n")
	for _, e := range edges {
		builder.WriteString(fmt.Sprintf("  \"%s\" -> \"%s\" [label=\"%s\"];\n", e.SourceID, e.TargetID, e.RelationshipType))
	}

	builder.WriteString("}\n")
	return builder.String(), nil
}

// JSONExporter implements Exporter for JSON schema
type JSONExporter struct{}

func (j *JSONExporter) Export(nodes []store.DBNode, edges []store.DBEdge) (string, error) {
	payload := map[string]interface{}{
		"metadata": map[string]string{
			"version":   "v1.0.0",
			"generated": time.Now().Format(time.RFC3339),
		},
		"nodes": nodes,
		"edges": edges,
	}

	b, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// PNGExporter implements Exporter for PNG format via Kroki API
type PNGExporter struct{}

func (p *PNGExporter) Export(nodes []store.DBNode, edges []store.DBEdge) (string, error) {
	// First, generate the DOT syntax
	dotExp := &DOTExporter{}
	dotStr, err := dotExp.Export(nodes, edges)
	if err != nil {
		return "", err
	}

	// Send to Kroki API
	req, err := http.NewRequest("POST", "https://kroki.io/graphviz/png", strings.NewReader(dotStr))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "text/plain")

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to reach kroki.io API: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("kroki.io returned status: %d", resp.StatusCode)
	}

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	return string(bodyBytes), nil
}
